### ISSUE TITLE
Tiny Bug in Usage Output

### ISSUE THREAD

**Issue by Losk-x** [pohchaichon/learned_index_benchmark#2]
https://github.com/gre4index/GRE/blob/57cff1c8f9a61244c1c5802cf88cb058ae53624a/datasets/generator.cpp#L608

The related code is correct, but the hint is a little bit wrong.
"Local epsilon >= global_epilon" 
shoule be "Local epsilon <= global_epilon"

**Comment by pohchaichon** [comment]
Fixed bec096f. Thanks!
