### ISSUE TITLE
ALEX+ Can not run

### ISSUE THREAD

**Issue by cszzy** [pohchaichon/learned_index_benchmark#4]
Hi，
When I evaluate ALEX+, I try to insert some kvs into an empty ALEX+ in single thread, and it seems that the program meet a deadlock.
Hope the author could fix the problem. Thanks a lot!

**Comment by pohchaichon** [comment]
ALEX+ does not implemented the SMO at the root node yet as our experiments only concern bulkloaded tree.
Inserting into empty tree will trigger such SMO. You may bulkload more kv for now.
