### ISSUE TITLE
data_generator parameters

### ISSUE THREAD

**Issue by min-guk** [pohchaichon/learned_index_benchmark#6]
Thanks for sharing such a great benchmark framework for learned index.
I would like to run an experiment with the same synthetic data you used in paper.

Could you please tell me the exact parameter values of generator for creating below synthetic data?

syn_ghard_leasy, syn_geasy_lhard, syn_ghard_lhard

./generator {le} {ge} {lv} {gv} {num} {path}

Thank you.

**Comment by pohchaichon** [comment]
le and ge are 32 and 4096 respectively as that is the epsilon chosen in the paper.

lv and gv can be obtained the from reading x and y value of Figure 14 (it doesn't need to be exact).
For your information:
syn_ghard_leasy: lv = 6000, ev = 6000
syn_geasy_lhard: lv = 1171555, ev = 1
syn_ghard_lhard: lv = 1213455, ev = 6000

Unfortunately, the current generator sometimes does not produce exactly the input lv and gv, you need to input a little higher than what you want. That might required some tuning.

**Comment by min-guk** [comment]
Thank you!
